project:
  type: website
  output-dir: .

website:
  title: "Alomoy"
  favicon: css/img/logo.png
  repo-url: https://github.com/alomoy/

format:
  revealjs:
    theme: sky
    transition: convex
    slide-number:  c/t
    navigation-mode: vertical
    controls-layout: bottom-right
    css:
    - css/styles.css
    - styles.css
    logo: css/logo.png
    footer: '<a href="https://www.alomoy.net" target="_blank">www.alomoy.net</a> | Press space or arrow to change slides'
revealjs-plugins:
  - qdraw



