---
title: "The Quranic Verses on Earth"
subtitle: ""
author: Abdullah Al Mahmud
format: html
---

[View the PDF here](quran_earth_verses.pdf)

Please verify accuracy. There might be issues here ...

## 1. Allah has made the earth a bed

- <a href="https://tanzil.net/#2:22">2:22</a> لَّذِي جَعَلَ لَكُمُ الْأَرْضَ فِرَاشًا وَالسَّمَاءَ بِنَاءً - It is He who made for you the earth a bed [spread out] and the sky a canopy and sent down from the sky rain and brought forth thereby fruits as provision for you. So do not attribute to Allah equals while you know [that there is nothing similar to Him].

- <a href="https://tanzil.net/#20:53">20:53</a> الَّذِي جَعَلَ لَكُمُ الْأَرْضَ مَهْدًا وَسَلَكَ لَكُمْ فِيهَا سُبُلًا - [It is He] who has made for you the earth as a bed and inserted therein for you roadways and sent down from the sky, rain and produced thereby categories of various plants.

- <a href="https://tanzil.net/#43:10">43:10</a>  الَّذِي جَعَلَ لَكُمُ الْأَرْضَ مَهْدًا وَجَعَلَ لَكُمْ فِيهَا سُبُلًا لَّعَلَّكُمْ تَهْتَدُونَ  - [He] who made for you the earth a bed and made for you upon it roads that you might be guided.

- <a href="https://tanzil.net/#51:48">51:48</a> وَالْأَرْضَ فَرَشْنَاهَا فَنِعْمَ الْمَاهِدُونَ - And the earth We have spread out, and excellent is the preparer.

- <a href="https://tanzil.net/#71:19">71:19</a> وَاللَّهُ جَعَلَ لَكُمُ الْأَرْضَ بِسَاطًا  - And Allah has made the earth for you as a carpet.

- <a href="https://tanzil.net/#78:6">78:6</a>  أَلَمْ نَجْعَلِ الْأَرْضَ مِهَادًا - Have We not made the earth a resting place?


  ## 2. Earth Spread Out
- <a href="https://tanzil.net/#13:3">13:3</a>وَهُوَ الَّذِي مَدَّ الْأَرْضَ وَجَعَلَ فِيهَا رَوَاسِيَ وَأَنْهَارًا ۖ – And it is He who spread the earth and placed therein firmly set mountains and rivers...
- <a href="https://tanzil.net/#15:19">15:19</a>وَالْأَرْضَ مَدَدْنَاهَا وَأَلْقَيْنَا فِيهَا رَوَاسِيَ – And the earth We have spread it and cast therein firmly set mountains...
- <a href="https://tanzil.net/#67:24">67:24</a> – Say, “It is He who has multiplied you throughout the earth, and to Him you will be gathered.”
- <a href="https://tanzil.net/#91:6">91:6</a> – And [by] the earth and He who spread it.
- <a href="https://tanzil.net/#50:7">50:7</a> – And the earth – We spread it out and cast therein firmly set mountains...
- <a href="https://tanzil.net/#51:48">51:48</a> – And the earth – We have spread it, and excellent is the preparer.
- <a href="https://tanzil.net/#88:20">88:20</a> – And at the earth – how it is spread out?

## 3. Earth Made Tame
- <a href="https://tanzil.net/#67:15">67:15</a> هُوَ الَّذِي جَعَلَ لَكُمُ الْأَرْضَ ذَلُولًا فَامْشُوا فِي مَنَاكِبِهَا – It is He who made the earth tame for you – so walk among its slopes and eat of His provision – and to Him is the resurrection.

## 4. Everything Created for You
- <a href="https://tanzil.net/#2:29">2:29</a>هُوَ الَّذِي خَلَقَ لَكُم مَّا فِي الْأَرْضِ جَمِيعًا  – It is He who created for you all of that which is on the earth. Then He directed Himself to the heaven...

## 5. Knowledge of the Unseen
- <a href="https://tanzil.net/#2:33">2:33</a>إِنِّي أَعْلَمُ غَيْبَ السَّمَاوَاتِ وَالْأَرْضِ – Do you not know that I know the unseen [aspects] of the heavens and the earth?

## 6. Signs in Heavens & Earth
- <a href="https://tanzil.net/#2:164">2:164</a>, <a href="https://tanzil.net/#3:190">3:190</a> إِنَّ فِي خَلْقِ السَّمَاوَاتِ وَالْأَرْضِ وَاخْتِلَافِ اللَّيْلِ وَالنَّهَارِ لَآيَاتٍ لِّأُولِي الْأَلْبَابِ, <a href="https://tanzil.net/#10:6">10:6</a>, <a href="https://tanzil.net/#12:105">12:105</a>, <a href="https://tanzil.net/#45:3">45:3</a>, <a href="https://tanzil.net/#45:5">45:5</a>, <a href="https://tanzil.net/#51:20">51:20</a>
*(Indeed, in the creation of the heavens and the earth... are signs for those of understanding.)*

## 7. Reviving Earth by Rain
- <a href="https://tanzil.net/#30:50">30:50</a>فَانظُرْ إِلَىٰ آثَارِ رَحْمَتِ اللَّهِ كَيْفَ يُحْيِي الْأَرْضَ بَعْدَ مَوْتِهَا – Look at the effects of the mercy of Allah – how He gives life to the earth after its lifelessness...
(Also: 2:164, 16:65, 22:5, 22:63, 29:63, 35:9, 36:33, 45:5, 57:17)

## 8. Submission of All
- <a href="https://tanzil.net/#3:83">3:83</a>أَفَغَيْرَ دِينِ اللَّهِ يَبْغُونَ وَلَهُ أَسْلَمَ مَن فِي السَّمَاوَاتِ وَالْأَرْضِ طَوْعًا وَكَرْهًا – So is it other than the religion of Allah they desire, while to Him have submitted [all] those within the heavens and earth...?

## 9. Paradise as Wide as Heavens & Earth
- <a href="https://tanzil.net/#3:133">3:133</a>وَسَارِعُوا إِلَىٰ مَغْفِرَةٍ مِّن رَّبِّكُمْ وَجَنَّةٍ عَرْضُهَا السَّمَاوَاتُ وَالْأَرْضُ أُعِدَّتْ لِلْمُتَّقِينَ  – And hasten to forgiveness from your Lord and a garden as wide as the heavens and earth...

## 10. Travel Earth, See Fate of Disbelievers

فَسِيرُوا فِي الْأَرْضِ فَانظُرُوا كَيْفَ كَانَ عَاقِبَةُ الْمُكَذِّبِينَ

- <a href="https://tanzil.net/#3:137">3:137</a>, <a href="https://tanzil.net/#6:11">6:11</a>, <a href="https://tanzil.net/#9:2">9:2</a>, <a href="https://tanzil.net/#12:109">12:109</a>, <a href="https://tanzil.net/#16:36">16:36</a>, <a href="https://tanzil.net/#27:69">27:69</a>, <a href="https://tanzil.net/#30:42">30:42</a>, <a href="https://tanzil.net/#35:44">35:44</a>, <a href="https://tanzil.net/#40:21">40:21</a>, <a href="https://tanzil.net/#40:82">40:82</a>, <a href="https://tanzil.net/#47:10">47:10</a>

## 11. Reflection on Creation
- <a href="https://tanzil.net/#3:191">3:191</a>  – Who remember Allah... and give thought to the creation of the heavens and the earth...

## 12. Observation of the Realm
- <a href="https://tanzil.net/#7:185">7:185</a>فَسِيرُوا فِي الْأَرْضِ فَانظُرُوا كَيْفَ كَانَ عَاقِبَةُ الْمُكَذِّبِينَ – Do they not look into the realm of the heavens and the earth...?

## 13. Creation Not in Vain
- <a href="https://tanzil.net/#38:27">38:27</a>مَا خَلَقْنَا السَّمَاءَ وَالْأَرْضَ وَمَا بَيْنَهُمَا بَاطِلًا ۚ – And We did not create the heaven and earth and that between them in play...
(Also: 15:85, 16:3, 29:44, 30:8, 30:19, 30:24, 39:5, 44:38, 45:22, 46:3, 64:3)

## 14. Mountains as Stabilizers

وَأَلْقَىٰ فِي الْأَرْضِ رَوَاسِيَ أَن تَمِيدَ
- <a href="https://tanzil.net/#16:15">16:15</a>, <a href="https://tanzil.net/#21:31">21:31</a>, <a href="https://tanzil.net/#31:10">31:10</a>

## 15. Reducing Land from Borders

أَوَلَمْ يَرَوْا أَنَّا نَأْتِي الْأَرْضَ نَنقُصُهَا

- <a href="https://tanzil.net/#13:41">13:41</a>, <a href="https://tanzil.net/#21:44">21:44</a>

## 16. Earth Swallowing the Wicked

أَفَأَمِنَ الَّذِينَ مَكَرُوا السَّيِّئَاتِ أَن يَخْسِفَ اللَّهُ بِهِمُ الْأَرْضَ

- <a href="https://tanzil.net/#16:45">16:45</a> – Then, do those who have planned evil feel secure that Allah will not cause the earth to swallow them...?

## 17. Man Cannot Pierce Earth

إِنَّكَ لَن تَخْرِقَ الْأَرْضَ وَلَن تَبْلُغَ الْجِبَالَ

- <a href="https://tanzil.net/#17:37">17:37</a> – Indeed, you will never tear the earth [apart], and you will never reach the mountains in height.

## 18. Earth & Ships Made Subject
- <a href="https://tanzil.net/#22:65">22:65</a>أَلَمْ تَرَ أَنَّ اللَّهَ سَخَّرَ لَكُم مَّا فِي الْأَرْضِ وَالْفُلْكَ تَجْرِي فِي الْبَحْرِ – Do you not see that Allah has made subject to you whatever is on the earth and the ships...?

## 19. Earth Made Habitable
- <a href="https://tanzil.net/#27:61">27:61</a>أَمَّن جَعَلَ الْأَرْضَ قَرَارًا  – Is He [not best] who made the earth a stable ground and placed within it rivers...

## 20. Travel Earth & Observe Creation
- <a href="https://tanzil.net/#29:20">29:20</a>لْ سِيرُوا فِي الْأَرْضِ فَانظُرُوا كَيْفَ بَدَأَ الْخَلْقَ ۚ – Say, [O Muhammad], “Travel through the land and observe how He began creation...”

## 21. Allah Knows What Enters/Emerges
- <a href="https://tanzil.net/#34:2">34:2</a>يَعْلَمُ مَا يَلِجُ فِي الْأَرْضِ وَمَا يَخْرُجُ مِنْهَا – He knows what penetrates into the earth and what emerges from it and what descends from the heaven...

## 22. Sky & Earth Before & Behind
- <a href="https://tanzil.net/#34:9">34:9</a> – Then have they not considered what is before them and what is behind them of the heaven and earth...?

## 23. Allah Holds Heavens & Earth
- <a href="https://tanzil.net/#35:41">35:41</a>إِنَّ اللَّهَ يُمْسِكُ السَّمَاوَاتِ وَالْأَرْضَ أَن تَزُولَا ۚ – Indeed, Allah holds the heavens and the earth, lest they cease...

## 24. Lord of Heavens & Earth
- <a href="https://tanzil.net/#37:5">37:5</a> – [He is] Lord of the heavens and the earth and whatever is between them...

## 25. Earth Created in Two Days
- <a href="https://tanzil.net/#41:9">41:9</a> قُلْ أَئِنَّكُمْ لَتَكْفُرُونَ بِالَّذِي خَلَقَ الْأَرْضَ فِي يَوْمَيْنِ وَتَجْعَلُونَ لَهُ أَندَادًا ۚ ذَٰلِكَ رَبُّ الْعَالَمِينَ ‎﴿٩﴾‏ وَجَعَلَ فِيهَا رَوَاسِيَ مِن فَوْقِهَا وَبَارَكَ فِيهَا وَقَدَّرَ فِيهَا أَقْوَاتَهَا فِي أَرْبَعَةِ أَيَّامٍ سَوَاءً لِّلسَّائِلِينَ – Say, “Do you indeed disbelieve in He who created the earth in two days...?*

## 26. Creation in Six Days
- <a href="https://tanzil.net/#50:38">50:38</a>وَلَقَدْ خَلَقْنَا السَّمَاوَاتِ وَالْأَرْضَ وَمَا بَيْنَهُمَا فِي سِتَّةِ أَيَّامٍ وَمَا مَسَّنَا مِن لُّغُوبٍ  – And We did certainly create the heavens and earth and what is between them in six days...

## 27. Seven Heavens & Earth
- <a href="https://tanzil.net/#65:12">65:12</a>اللَّهُ الَّذِي خَلَقَ سَبْعَ سَمَاوَاتٍ وَمِنَ الْأَرْضِ مِثْلَهُنَّ يَتَنَزَّلُ الْأَمْرُ بَيْنَهُنَّ  – It is Allah who has created seven heavens and of the earth, the like of them...

## 28. Earthquake as Punishment
- <a href="https://tanzil.net/#67:16">67:16</a>‏ أَأَمِنتُم مَّن فِي السَّمَاءِ أَن يَخْسِفَ بِكُمُ الْأَرْضَ فَإِذَا هِيَ تَمُورُ  – Do you feel secure that He who [holds authority] in the heaven would not cause the earth to swallow you...?

## 29. Splitting of the Earth
- <a href="https://tanzil.net/#80:26">80:26</a>ثُمَّ شَقَقْنَا الْأَرْضَ شَقًّ – Then We broke open the earth, splitting [it with sprouts].

## 30. Earth Spread After Creation
- <a href="https://tanzil.net/#79:30">79:30</a>وَالْأَرْضَ بَعْدَ ذَٰلِكَ دَحَاهَا – And after that He spread the earth.

# Akhirah

## 1. The Hour Weighs Heavy on the Heavens and the Earth
- <a href="https://tanzil.net/#7:187">7:187</a>هُوَ ۚ ثَقُلَتْ فِي السَّمَاوَاتِ وَالْأَرْضِ – They ask you, [O Muhammad], about the Hour: when is its arrival? Say, "Its knowledge is only with my Lord. None will reveal its time except Him. It lays heavily upon the heavens and the earth. It will not come upon you except unexpectedly." They ask you as if you are familiar with it. Say, "Its knowledge is only with Allah, but most of the people do not know."

## 2. Earth and Heavens Replaced
- <a href="https://tanzil.net/#14:48">14:48</a>يَوْمَ تُبَدَّلُ الْأَرْضُ غَيْرَ الْأَرْضِ وَالسَّمَاوَاتُ ۖ – [It will be] on the Day the earth will be replaced by another earth, and the heavens [as well], and all creatures will come out before Allah, the One, the Prevailing.

## 3. Creature from the Earth
- <a href="https://tanzil.net/#27:82">27:82</a>وَإِذَا وَقَعَ الْقَوْلُ عَلَيْهِمْ أَخْرَجْنَا لَهُمْ دَابَّةً مِّنَ الْأَرْضِ تُكَلِّمُهُمْ أَنَّ النَّاسَ كَانُوا بِآيَاتِنَا لَا يُوقِنُونَ – And when the word befalls them, We will bring forth for them a creature from the earth speaking to them, [saying] that the people were, of Our verses, not certain [in faith].

## 4. Earth in His Grip
- <a href="https://tanzil.net/#39:67">39:67</a> – They have not appraised Allah with true appraisal, while the whole earth will be within His grip on the Day of Resurrection, and the heavens will be folded in His right hand. Exalted is He and high above what they associate with Him.

## 5. What the Earth Consumes
- <a href="https://tanzil.net/#50:4">50:4</a>وَمَا قَدَرُوا اللَّهَ حَقَّ قَدْرِهِ وَالْأَرْضُ جَمِيعًا قَبْضَتُهُ يَوْمَ الْقِيَامَةِ وَالسَّمَاوَاتُ مَطْوِيَّاتٌ بِيَمِينِهِ – We know what the earth diminishes of them, and with Us is a retaining record.

## 6. Earth Breaks Open
- <a href="https://tanzil.net/#50:44">50:44</a>يَوْمَ تَشَقَّقُ الْأَرْضُ عَنْهُمْ سِرَاعًا ۚ ذَٰلِكَ حَشْرٌ عَلَيْنَا يَسِيرٌ – The Day the earth breaks away from them and they emerge rapidly; that is a gathering easy for Us.

## 7. Earth Shaken
- <a href="https://tanzil.net/#56:4">56:4</a>إِذَا رُجَّتِ الْأَرْضُ رَجًّا – When the earth is shaken with convulsion.

## 8. Earth and Mountains Leveled
- <a href="https://tanzil.net/#69:14">69:14</a>وَحُمِلَتِ الْأَرْضُ وَالْجِبَالُ فَدُكَّتَا دَكَّةً وَاحِدَةً  – And the earth and the mountains are lifted and leveled with one blow.

## 9. Mountains Become Sand
- <a href="https://tanzil.net/#73:14">73:14</a>يَوْمَ تَرْجُفُ الْأَرْضُ وَالْجِبَالُ وَكَانَتِ الْجِبَالُ كَثِيبًا مَّهِيلًا – On the Day the earth and the mountains will convulse and the mountains will become a heap of sand pouring down.

## 10. Earth Extended (leveled)
- <a href="https://tanzil.net/#84:3">84:3</a>وَإِذَا الْأَرْضُ مُدَّتْ  – And when the earth has been extended.

## 11. Earth Crushed
- <a href="https://tanzil.net/#89:21">89:21</a>كَلَّا إِذَا دُكَّتِ الْأَرْضُ دَكًّا دَكًّا – No! When the earth has been leveled – pounded and crushed.

## 12. Earthquake of the Hour
- <a href="https://tanzil.net/#99:1">99:1</a>إِذَا زُلْزِلَتِ الْأَرْضُ زِلْزَالَهَا – When the earth is shaken with its [final] earthquake.

## 13. Earth Discharges Its Burdens
- <a href="https://tanzil.net/#99:2">99:2</a>وَأَخْرَجَتِ الْأَرْضُ أَثْقَالَهَا – And the earth discharges its burdens.
