# (APPENDIX) পরিশিষ্ট {- #appendix}

এ অংশটি ওয়েবসাইটের জন্য আলাদাভাবে তৈরি করা হয়েছে।

# নির্বাচিত অংশ{- #selected}


## পরিপূর্ণ মানুষ{- #perfect-man}


মানুষ বলতে পরিপূর্ণ মানুষ বুঝায়। মানুষকে পূর্ণ হতে হলে তাকে সব যোগ্যতাই অর্জন করতে হবে। মুসলমানদের ক্ষেত্রে এটা আরও বেশি সত্য। মুসলমানদের আল্লাহ উত্থান ঘটিয়েছেন পৃথিবীর মানুষকে ভালো কাজের নির্দেশ দেয়া এবং মন্দ কাজ থেকে বিরত রাখার জন্যে। অন্য কথায় পৃথিবীর নেতৃত্ব দেয়ার জন্যে। নেতৃত্ব দিতে হলে তো সব যোগ্যতাই তাদের অর্জন করতে হবে। অন্তত প্রতিটি মুসলমানকে একই সাথে গৃহী, পুলিশ ও সৈনিকের ভূমিকা পালনের মত যোগ্যতা অর্জন করতেই হবে। ইতিহাস বলে এই যোগ্যতা যখন আমরা হারিয়ে ফেলতে শুরু করেছি, মুসলমানদের পতন শুরু হয়েছে তখন থেকেই।



- সাইমুম ১৮ (ব্ল্যাক ক্রসের মুখোমুখি)



## আহমদ মুসার সূক্ষ্ম পর্যবেক্ষণ{- #meticulousness}


চোখ খুলল আহমদ মুসা। চোখ খোলার পর তার চোখ ঘরের তিন দিকে ঘুরে এল। হাসপাতালের সুসজ্জিত একটা কক্ষ।

দরজার পর্দায় সুন্দর করে লেখা, ‘কুইন এলিজাবেথ হাসপাতাল।’

মাথায় হাত না দিয়েই বুঝল, গোটা মাথায় তার ব্যান্ডেজ। মাথা ভারি এবং বেদনা।

মাথা বাঁদিকে একটু ঘুরাতেই আহমদ মুসা ডাঃ মারিয়া মার্গারেটকে দেখতে পেল।

ডাঃ মার্গারেট এল আহমদ মুসার সামনে।

‘গুড ইভনিং ডাক্তার।’

‘ওয়েলকাম আহমদ আবদুল্লাহ।’বলে একটু ভাবল ডাঃ মার্গারেট। তারপর বলল, ‘গুড ইভনিং বললবেন কেন, কি করে বুঝলেন যে এখন বিকেল?’

‘টেবিলের ফুলদানিতে তাজা ফুল দেখে। সাধারণত হাসপাতালের কক্ষগুলোতে বিকেলে ফুল সরবরাহ করা হয়।’

‘স্থান বিশেষে নিয়ম তো আলাদাও হতে পারে।’

‘হাসপাতালের সকালটা খুব ব্যস্ত সময়। এ সময় হাসপাতালে ফুল সরবরাহের পরিবেশ থাকে না। তবে আরও কিছু কারণ আছে।’

ডাঃ মার্গারেট কিছুটা অবাক হলো। বলতে গেলে বেশির ভাগ সময় হাসপাতালে কাটে, কিন্তু সেতো এ বিষয়টা এতদিন লক্ষ্য করেনি! বলল, ‘সে কারণগুলো কি?’

আহমদ মুসার ঠোঁটে ঈষৎ হাসি। বলল, ‘প্রথমত, আমার ক্ষুধা। মনে হচ্ছে, খাওয়ার পর অন্তত পাঁচ ছয় ঘন্টা পার হয়েছে। দ্বিতীয়ত, আপনার ক্লান্তি। দীর্ঘ সময় আপনি ডিউটিতে আছেন। কিন্তু আপনার চোখে-মুখে রাত জাগার চাপ নেই।’

ডাঃ মার্গারেটের চোখে-মুখে ফুটে উঠল বিস্ময়। বলল, ‘সামান্য কয়েক মুহূর্তে আপনি এত জিনিস খেয়াল করেছেন! এত সুক্ষ্ণ বিষয় আপনার চোখে পড়ে! আপনার পরিচয় কি? পেশা কি?’

‘আমার পাসপোর্টে কিছু তো পেয়েছেন?’

‘আপনার পাসপোর্ট আমি দেখেছি কি করে বুঝলেন?’ডাঃ মার্গারেটের কণ্ঠে আবারও বিস্ময়।

‘পাসপোর্টে লেখা আমার পূর্ণ নাম আপনার মুখে শুনেছি।’

ডাঃ মার্গারেট টেবিলের পাশের চেয়ারটিতে ধপ করে বসে পড়ল।

তার চোখে মুখে প্রবল উৎসুক্য। বলল, ‘বলুন তো আপনার পকেট থেকে কিছু খোয়া গেছে কিনা?’

‘না খোয়া যায়নি।’

‘কি করে নিশ্চিত হলেন আপনি এতটা?’

‘আপনার প্রশ্ন থেকে?’

‘আমার প্রশ্ন থেকে?’বিস্ময়ে চোখ কপালে তুলে বলল ডাঃ মার্গারেট।

‘হ্যাঁ।আপনার প্রশ্ন থেকে বুঝা যাচ্ছে, খোয়া যাওয়ার মত কিছু আমার পকেটে ছিল যা আপনি দেখেছেন। যখন দেখেছেন, তখন তা খোয়া যাওয়ার কথা নয়।’

এবার ডাঃ মার্গারেটের চোখে বিস্ময় বিমুগ্ধ দৃষ্টি। বলল, ‘আপনি শার্লক হোমস-এর মত কোন গোয়েন্দা নাকি? এমন সুক্ষ্ণ বিশ্লেষণ সাধারণ মাথার কাজ নয়।’

- আটলান্টিকের ওপারে


# Feedback{-}



Nothing yet

