# সুরাহসমূহ {- #surah} 

এ অংশে থাকবে সুরাহগুলোর নামের অর্থ, নাযিলের সময়কাল ও সংক্ষিপ্ত আলোচ্যসূচি। 

# দারসুল কুরআন {- #dars} 


# বিষয়ভিত্তিক কুরআন {- #quran-index} 

## ক {- #k}

### করযে হাসানা (আল্লাহকে)  {-} 

সুরা বাক্বারা:

> مَّن ذَا الَّذِي يُقْرِضُ اللَّهَ قَرْضًا حَسَنًا فَيُضَاعِفَهُ لَهُ أَضْعَافًا كَثِيرَةً ۚ وَاللَّهُ يَقْبِضُ وَيَبْسُطُ وَإِلَيْهِ تُرْجَعُونَ

> অর্থ: এমন কে আছে আল্লাহকে করয দেবে, উত্তম করয? অতঃপর আল্লাহ তা বহুগুণ বাড়িয়ে ফেরত দেবেন। আল্লাহই তো সঙ্কুচিত ও প্রশস্ত করেন। তাঁরই দিকে তোমাদেরকে ফিরে যেতে হবে। 
> ---  [সুরাহ বাক্বারা, ২:২৪৫](https://tanzil.net/#2:245)   

সুরাহ মায়িদা:

> وَقَالَ اللَّهُ إِنِّي مَعَكُمْ ۖ لَئِنْ أَقَمْتُمُ الصَّلَاةَ وَآتَيْتُمُ الزَّكَاةَ وَآمَنتُم بِرُسُلِي وَعَزَّرْتُمُوهُمْ وَأَقْرَضْتُمُ اللَّهَ قَرْضًا حَسَنًا لَّأُكَفِّرَنَّ عَنكُمْ سَيِّئَاتِكُمْ وَلَأُدْخِلَنَّكُمْ جَنَّاتٍ تَجْرِي مِن تَحْتِهَا الْأَنْهَارُ

> অর্থ: আল্লাহ (বনী ঈসরাইলকে) বলেছিলেন, আমি তোমাদের সঙ্গে আছি; যদি তোমরা সালাত কায়েম কর, যাকাত আদায় কর, আমার রাসুলদের প্রতি ঈমান আনো ও তাঁদের সাহায্য কর এবং আল্লাহকে করযে হাসানা (উত্তম ঋণ) দাও, তাহলে আমি অবশ্যই তোমাদের গুনাহ মাফ করে দেব এবং তোমাদেরকে প্রবেশ করাবো বাগানুসমূহে (জান্নাতে), যেগুলোর তলদেশ দিয়ে নহর প্রবাহিত। 
>
> --- [সুরা মায়িদা, ৫:১২](https://tanzil.net/#5:12) 



## জ {- #j}

### জান্নাত আসমান ও পৃথিবীর মতো বিশাল {- #zannah-size} 

সুরা আলে ইমরান:

> وَسَارِعُوا إِلَىٰ مَغْفِرَةٍ مِّن رَّبِّكُمْ وَجَنَّةٍ عَرْضُهَا السَّمَاوَاتُ وَالْأَرْضُ أُعِدَّتْ لِلْمُتَّقِينَ

> অর্থ: ছুটে চলো তোমাদের রবের ক্ষমা ও সেই জান্নাতের দিকে, যা আকাশ ও পৃথিবীর মতো প্রশস্ত। যা প্রস্তুত করে রাখা হয়েছে মুত্তাকীদের জন্যে। 
> --- [সুরাহ আলে ইমরান, ৩:১৩৩](https://tanzil.net/#3:133) 

সুরাহ হাদিদ:

>سَابِقُوا إِلَىٰ مَغْفِرَةٍ مِّن رَّبِّكُمْ وَجَنَّةٍ عَرْضُهَا كَعَرْضِ السَّمَاءِ وَالْأَرْضِ أُعِدَّتْ لِلَّذِينَ آمَنُوا بِاللَّهِ وَرُسُلِهِ ۚ

> অর্থ: এগিয়ে চলো তোমাদের রবের ক্ষমা ও জান্নাতের দিকে, যা আকাশ ও পৃথিবীর মতো প্রশস্ত, যা প্রস্তুত করে রাখা হয়েছে আল্লাহ ও তাঁর রাসুলদের প্রতি বিশ্বাসস্থাপনকারীদের জন্যে। 
>
> --- [সুরাহ হাদিদ, ৫৭:২১](https://tanzil.net/#57:21) 

আরও: 

- [সুরাহ হাদিদ, ৫৭:১৮](https://tanzil.net/#57:11)
- [সুরাহ হাদিদ, ৫৭:১৮](https://tanzil.net/#57:18)
- [সুরাহ তাগাবুন, ৬৪:১৭](https://tanzil.net/#64:17)
- [সুরাহ মুযযাম্মিল, ৭৩:২০](https://tanzil.net/#73:20)  

## প {- #p} 

### পৃথিবী ভ্রমণের নির্দেশ {- #traveling}

সুরাহ আলে ইমরান: 

> قَدۡ خَلَتۡ مِنۡ قَبۡلِكُمۡ سُنَنٌۙ فَسِيۡرُوۡا فِىۡ الۡاَرۡضِ فَانظُرُوۡا كَيۡفَ كَانَ عَاقِبَةُ الۡمُكَذِّبِيۡنَ

> অর্থ: তোমাদের আগে অনেক জীবনপদ্ধতি অতিবাহিত হয়েছে। পৃথিবীতে ভ্রমণ করে দেখোই না মিথ্যা প্রতিপন্নকারীদের পরিণাম কেমন হয়েছে।
>
> ---   [সুরাহ আলে ইমরান, আয়াত ৩:১৩৭](https://tanzil.net/#3:137)

সুরাহ আল মায়িদা:

> قُلْ سِيرُوا فِي الْأَرْضِ ثُمَّ انظُرُوا كَيْفَ كَانَ عَاقِبَةُ الْمُكَذِّبِينَ

> অর্থ: বলুন, পৃথিবীতে ঘুরে দেখে নাও মিথ্যা প্রতিপন্নকারীদের পরিণাম কেমন ছিল। 
> 
> --- [সুরাহ আল আন'আম, আয়াত ৬:১০-১১](https://tanzil.net/#6:11) 

আরও দেখুন [এখানে](../islam/travelling.al) 

## স {- #s} 

### সৎ কাজের নির্দেশ {- #enjoining-on-good-deeds}

> وَلْتَكُن مِّنكُمْ أُمَّةٌ يَدْعُونَ إِلَى الْخَيْرِ وَيَأْمُرُونَ بِالْمَعْرُوفِ وَيَنْهَوْنَ عَنِ الْمُنكَرِ ۚ وَأُولَٰئِكَ هُمُ الْمُفْلِحُونَ

> অর্থ: তোমাদের মধ্যে এমন একটি দল থাকা উচিত যারা মানুষকে ভাল কাজের দিকে আহ্বান জানাবে, সৎ কাজের আদেশ দেবে ও মন্দ কাজ থেকে নিষেধ করবে। তারাই সফলকাম। 
>
> ---  [ সুরা আলে ইমরান ৩:১০৪ ](https://tanzil.net/#3:104) 


- [সুরা আলে ইমরান ৩:১১০](https://tanzil.net/#3:110) 
 
- [সুরা আরাফ, ৭:১৯৯](https://tanzil.net/#7:199) 

- [সুরা তাওবা, ৯:৭১](https://tanzil.net/#9:71)
